### ISSUE TITLE
Invalid AST and generated Elixir code for anonymous function captures

### ISSUE THREAD

**Issue by bartblast** [hrzndhrn/beam_file#20]
Hey Marcus,

I found a bug related to anonymous function captures. It may have existed in previous versions of BeamFile, but Hologram's tests didn't catch it since all the anonymous function capture tests were of the form that allowed the compiler to replace the code with a named function capture (e.g., &(&1 + &2) can be replaced with &:erlang.+/2). So I can't point out the BeamFile version that introduced the bug or whether it was there from the beginning.

Here's an example of code that produces invalid output:

source file:
```elixir
defmodule MyModule do
  def my_fun do
    &(&1 * &2 + &1)
  end
end
```

$ mix beam.file --elixir MyModule
```elixir
defmodule Elixir.MyModule do
  def my_fun do
    fn capture, capture -> :erlang.+(:erlang.*(capture, capture), capture) end
  end
end
```

iex> BeamFile.elixir_quoted!(MyModule)
```elixir
{:defmodule, [context: Elixir, import: Kernel],
 [
   {:__aliases__, [alias: false], [MyModule]},
   [
     do: {:__block__, [],
      [
        {:def, [line: 2, column: 7],
         [
           {:my_fun, [], Elixir},
           [
             do: {:fn, [line: 3, column: 15],
              [
                {:->, [line: 3, column: 15],
                 [
                   [
                     {:capture,
                      [version: 0, counter: {MyModule, 2}, line: 3, column: 7],
                      nil},
                     {:capture,
                      [version: 1, counter: {MyModule, 3}, line: 3, column: 12],
                      nil}
                   ],
                   {{:., [line: 3, column: 15], [:erlang, :+]},
                    [line: 3, column: 15],
                    [
                      {{:., [line: 3, column: 10], [:erlang, :*]},
                       [line: 3, column: 10],
                       [
                         {:capture,
                          [
                            version: 0,
                            counter: {MyModule, 2},
                            line: 3,
                            column: 7
                          ], nil},
                         {:capture,
                          [
                            version: 1,
                            counter: {MyModule, 3},
                            line: 3,
                            column: 12
                          ], nil}
                       ]},
                      {:capture,
                       [version: 0, counter: {MyModule, 2}, line: 3, column: 7],
                       nil}
                    ]}
                 ]}
              ]}
           ]
         ]}
      ]}
   ]
 ]}
```

As you probably noticed, the problem is that the parameters are always caled "capture" instead of using some form on an index, e.g. "capture1" and "capture2", etc.

**Comment by NickNeck** [comment]
I will take a look. Thanks.

**Comment by NickNeck** [comment]
Hi Bart, in Elixir 1.17 the form of the capture vars has changed and is now `{:capture, [counter: {MyModule, 5}, ...], nil}` instead of `{:x1, [...], nil}`. For the disassembled Elixir code, `beam_file` now generates vars as `{:"capture#{count}", ..., nil}` with the `count` from the `counter`. `BeamFile.elixir_quoted!/1` returns the same AST as before.

**Comment by bartblast** [comment]
Hey Marcus, thanks for explanation! Can you confirm that you are keeping the AST intact and I need to rewrite it on my end (possibly using similar strategy as you did in the normalizer)?

**Comment by NickNeck** [comment]
Yes. the "extended" AST returned by `elixir_quoted` is the same as before.
